# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=150, verbose_name='nombres')),
                ('apellidos', models.CharField(max_length=150, verbose_name='apellidos')),
                ('genero', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=1, verbose_name='género')),
                ('fecha_nacimiento', models.DateField(verbose_name='fecha de nacimiento')),
                ('fecha_ingreso', models.DateField(verbose_name='fecha de ingreso')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('CE', 'Cédula de extranjería'), ('PA', 'Pasaporte'), ('RC', 'Registro civil'), ('TI', 'Tarjeta de identidad'), ('AN', 'Adulto sin identificar'), ('MN', 'Menor sin identificar'), ('NU', 'Número único de identificación')], max_length=2, verbose_name='tipo de documento')),
                ('numero_documento', models.IntegerField(verbose_name='número de documento')),
                ('estado_civil', models.CharField(choices=[('V', 'Viudo'), ('C', 'Casado'), ('S', 'Soltero'), ('D', 'Divociado'), ('UL', 'Unión libre')], max_length=2, verbose_name='estado civil')),
                ('zona', models.CharField(choices=[('U', 'Urbano'), ('R', 'Rural')], max_length=1, verbose_name='zona')),
                ('direccion', models.CharField(max_length=200, verbose_name='dirección')),
                ('telefono', models.IntegerField(blank=True, null=True, verbose_name='telefono')),
                ('celular', models.IntegerField(blank=True, null=True, verbose_name='celular')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('grupo_sanguineo', models.CharField(blank=True, choices=[('O-', 'O+'), ('O+', 'O-'), ('AB', 'AB')], max_length=2, verbose_name='grupo sanguineo')),
                ('grupo_etnico', models.CharField(blank=True, choices=[('D', 'Desplazado'), ('I', 'Indigena'), ('N', 'Negro'), ('O', 'Otro')], max_length=1, verbose_name='grupo etnico')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name_plural': 'pacientes',
                'verbose_name': 'paciente',
            },
        ),
    ]
