# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacional', '0006_auto_20170722_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioAtencion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='titulo')),
                ('start', models.DateTimeField(verbose_name='inicio')),
                ('end', models.DateTimeField(verbose_name='final')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horario_atencion', to='organizacional.Empleado')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horario_atencion', to='organizacional.Sucursal')),
            ],
            options={
                'verbose_name_plural': 'agenda',
                'verbose_name': 'agenda',
            },
        ),
    ]
