# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 14:44
from __future__ import unicode_literals

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('duracion', models.DurationField(help_text='Duración de la atención para cada cita. Ingresar duración de la forma HH:MM:SS', verbose_name='duración')),
            ],
            options={
                'verbose_name': 'agenda',
                'verbose_name_plural': 'agendas',
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('NC', 'No confirmada'), ('CO', 'Confirmada'), ('CU', 'Cumplida'), ('CA', 'Cancelada'), ('EX', 'Excusada'), ('NA', 'No asistio')], max_length=2, verbose_name='estado')),
            ],
            options={
                'verbose_name': 'cita',
                'verbose_name_plural': 'citas',
            },
            bases=(common.models.UpdateModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HorarioAtencion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='titulo')),
                ('start', models.DateTimeField(verbose_name='inicio')),
                ('end', models.DateTimeField(verbose_name='final')),
            ],
            options={
                'verbose_name': 'horario de atención',
                'verbose_name_plural': 'horarios de atención',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=150, verbose_name='primer nombre')),
                ('segundo_nombre', models.CharField(blank=True, max_length=150, verbose_name='segundo nombre')),
                ('primer_apellido', models.CharField(max_length=150, verbose_name='primer apellido')),
                ('segundo_apellido', models.CharField(blank=True, max_length=150, verbose_name='segundo apellido')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('CE', 'Cédula de extranjería'), ('PA', 'Pasaporte'), ('RC', 'Registro civil'), ('TI', 'Tarjeta de identidad'), ('AN', 'Adulto sin identificar'), ('MN', 'Menor sin identificar'), ('NU', 'Número único de identificación')], max_length=2, verbose_name='tipo de documento')),
                ('numero_documento', models.CharField(max_length=20, unique=True, verbose_name='número de documento')),
                ('telefono', models.PositiveIntegerField(blank=True, null=True, verbose_name='telefono')),
                ('celular', models.IntegerField(blank=True, null=True, verbose_name='celular')),
                ('direccion', models.CharField(blank=True, max_length=200, verbose_name='dirección')),
            ],
            options={
                'verbose_name': 'persona',
                'verbose_name_plural': 'personas',
            },
            bases=(common.models.UpdateModelMixin, models.Model),
        ),
    ]
