# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 00:08
from __future__ import unicode_literals

import common.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacional', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('NC', 'No confirmada'), ('CO', 'Confirmada'), ('CU', 'Cumplida'), ('CA', 'Cancelada'), ('EX', 'Excusada'), ('NA', 'No asistio')], max_length=2, verbose_name='estado')),
            ],
            options={
                'verbose_name_plural': 'citas',
                'verbose_name': 'cita',
            },
            bases=(common.models.UpdateModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HorarioAtencion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='titulo')),
                ('start', models.DateTimeField(verbose_name='inicio')),
                ('end', models.DateTimeField(verbose_name='final')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horario_atencion', to='organizacional.Empleado')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horario_atencion', to='organizacional.Sucursal')),
            ],
            options={
                'verbose_name_plural': 'horarios de atención',
                'verbose_name': 'horario de atención',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=150, verbose_name='nombres')),
                ('apellidos', models.CharField(max_length=150, verbose_name='apellidos')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('CE', 'Cédula de extranjería'), ('PA', 'Pasaporte'), ('RC', 'Registro civil'), ('TI', 'Tarjeta de identidad'), ('AN', 'Adulto sin identificar'), ('MN', 'Menor sin identificar'), ('NU', 'Número único de identificación')], max_length=2, verbose_name='tipo de documento')),
                ('numero_documento', models.CharField(max_length=20, unique=True, verbose_name='número de documento')),
                ('telefono', models.PositiveIntegerField(blank=True, null=True, verbose_name='telefono')),
                ('celular', models.IntegerField(blank=True, null=True, verbose_name='celular')),
                ('direccion', models.CharField(blank=True, max_length=200, verbose_name='dirección')),
            ],
            options={
                'verbose_name_plural': 'personas',
                'verbose_name': 'persona',
            },
            bases=(common.models.UpdateModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='cita',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='agenda.HorarioAtencion', verbose_name='horario'),
        ),
        migrations.AddField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='agenda.Persona', verbose_name='paciente'),
        ),
    ]
