# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_auto_20170722_1703'),
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'cita',
                'verbose_name_plural': 'citas',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=150, verbose_name='nombres')),
                ('apellidos', models.CharField(max_length=150, verbose_name='apellidos')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('CE', 'Cédula de extranjería'), ('PA', 'Pasaporte'), ('RC', 'Registro civil'), ('TI', 'Tarjeta de identidad'), ('AN', 'Adulto sin identificar'), ('MN', 'Menor sin identificar'), ('NU', 'Número único de identificación')], max_length=2, verbose_name='tipo de documento')),
                ('numero_documento', models.CharField(max_length=20, unique=True, verbose_name='número de documento')),
                ('telefono', models.PositiveIntegerField(blank=True, null=True, verbose_name='telefono')),
                ('celular', models.IntegerField(blank=True, null=True, verbose_name='celular')),
            ],
        ),
        migrations.AlterModelOptions(
            name='horarioatencion',
            options={'verbose_name': 'horario de atención', 'verbose_name_plural': 'horarios de atención'},
        ),
        migrations.AddField(
            model_name='cita',
            name='fecha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='agenda.HorarioAtencion', verbose_name='fecha'),
        ),
        migrations.AddField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='agenda.Persona', verbose_name='paciente'),
        ),
        migrations.AddField(
            model_name='cita',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='servicios.Servicio', verbose_name='servicio'),
        ),
    ]
