# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacional', '0001_initial'),
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horarioatencion',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_atencion', to='organizacional.Empleado'),
        ),
        migrations.AddField(
            model_name='horarioatencion',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_atencion', to='organizacional.Sucursal'),
        ),
        migrations.AddField(
            model_name='cita',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='agenda.HorarioAtencion', verbose_name='horario'),
        ),
        migrations.AddField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='agenda.Persona', verbose_name='paciente'),
        ),
    ]
