# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        ('agenda', '0002_auto_20171004_1444'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='servicios.Servicio', verbose_name='servicio'),
        ),
        migrations.AddField(
            model_name='cita',
            name='sesion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pacientes.Sesion', verbose_name='sesión'),
        ),
    ]
