# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_auto_20170724_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('NC', 'No confirmada'), ('CO', 'Confirmada'), ('CU', 'Cumplida'), ('CA', 'Cancelada'), ('EX', 'Excusada'), ('NA', 'No asistio')], default='NC', max_length=2, verbose_name='estado'),
            preserve_default=False,
        ),
    ]
