# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-30 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_agenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='duracion',
            field=models.DurationField(help_text='Duración de la atención para cada cita. Ingresar duración de la forma HH:MM:SS', verbose_name='duración'),
        ),
    ]
