# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 20:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_cita_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'verbose_name': 'persona', 'verbose_name_plural': 'personas'},
        ),
        migrations.RenameField(
            model_name='cita',
            old_name='fecha',
            new_name='horario',
        ),
    ]
