# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 23:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0011_auto_20170820_2309'),
        ('agenda', '0005_auto_20170804_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='sesion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pacientes.Sesion', verbose_name='sesión'),
        ),
    ]
