# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='forma_pago',
            field=models.CharField(choices=[('E', 'Efectivo'), ('T', 'Tarjeta'), ('C', 'Consignación')], max_length=2, verbose_name='forma de pago'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='organizacional.Institucion', verbose_name='entidad que prestará el servicio'),
        ),
        migrations.AlterField(
            model_name='servicioorden',
            name='tipo_pago',
            field=models.CharField(blank=True, choices=[('CO', 'Coopago'), ('CM', 'Cuota moderadora')], max_length=2, verbose_name='tipo de pago'),
        ),
    ]
