# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 21:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicioorden',
            name='medico',
        ),
        migrations.RemoveField(
            model_name='servicioorden',
            name='orden',
        ),
        migrations.RemoveField(
            model_name='servicioorden',
            name='servicio',
        ),
        migrations.AlterModelOptions(
            name='sesion',
            options={'ordering': ['fecha'], 'verbose_name': 'sesión', 'verbose_name_plural': 'sesiones'},
        ),
        migrations.DeleteModel(
            name='ServicioOrden',
        ),
    ]
