# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_auto_20170825_0432'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion',
            name='autorizacion',
            field=models.CharField(blank=True, max_length=100, verbose_name='autorización'),
        ),
        migrations.AddField(
            model_name='sesion',
            name='estado',
            field=models.CharField(choices=[('NC', 'No confirmada'), ('CO', 'Confirmada'), ('CU', 'Cumplida'), ('CA', 'Cancelada'), ('EX', 'Excusada'), ('NA', 'No asistio')], default='NC', max_length=2, verbose_name='estado'),
        ),
        migrations.AddField(
            model_name='sesion',
            name='fecha_autorizacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de autorización'),
        ),
    ]
