# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 14:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_auto_20170606_2305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orden',
            old_name='empresa',
            new_name='plan',
        ),
    ]
