# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_auto_20170607_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='fecha_orden',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de la orden'),
        ),
    ]
