# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_auto_20170609_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acompanante',
            name='asistio',
            field=models.BooleanField(default=True, verbose_name='acompañante'),
        ),
    ]
