# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_auto_20170609_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicioorden',
            name='descuento',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='descuento'),
        ),
    ]
