# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0006_auto_20170609_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicioorden',
            name='descuento',
            field=models.PositiveIntegerField(default=0, verbose_name='descuento'),
        ),
    ]
