# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0007_auto_20170610_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acompanante',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, verbose_name='dirección'),
        ),
        migrations.AlterField(
            model_name='acompanante',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, verbose_name='nombre completo'),
        ),
        migrations.AlterField(
            model_name='acompanante',
            name='telefono',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='teléfono'),
        ),
    ]
