# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-01 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0008_auto_20170612_2339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'ordering': ['nombres', 'apellidos'], 'verbose_name': 'paciente', 'verbose_name_plural': 'pacientes'},
        ),
        migrations.AlterField(
            model_name='acompanante',
            name='asistio',
            field=models.BooleanField(default=True, verbose_name='asistio con acompañante'),
        ),
    ]
