# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 23:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizacional', '0006_auto_20170722_1703'),
        ('servicios', '0004_auto_20170722_1703'),
        ('pacientes', '0010_auto_20170707_0443'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioRealizar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_sesiones', models.PositiveIntegerField(default=1, verbose_name='número de sesiones')),
                ('valor', models.PositiveIntegerField(verbose_name='valor')),
                ('coopago', models.PositiveIntegerField(verbose_name='coopago/moderadora')),
            ],
            options={
                'verbose_name': 'servicio a realizar',
                'verbose_name_plural': 'servicios a realizar',
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='fecha')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='organizacional.Empleado', verbose_name='medico')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='pacientes.ServicioRealizar', verbose_name='servicio')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='organizacional.Sucursal', verbose_name='sucursal')),
            ],
            options={
                'verbose_name': 'sesión',
                'verbose_name_plural': 'sesiones',
            },
        ),
        migrations.RemoveField(
            model_name='orden',
            name='autorizacion',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='forma_pago',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='pendiente_autorizacion',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='sucursal',
        ),
        migrations.AddField(
            model_name='serviciorealizar',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_realizar', to='pacientes.Orden', verbose_name='orden'),
        ),
        migrations.AddField(
            model_name='serviciorealizar',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_realizar', to='servicios.Servicio', verbose_name='servicio'),
        ),
    ]
