# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacional', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucion',
            name='identificacion',
            field=models.CharField(max_length=50, unique=True, verbose_name='identificación'),
        ),
    ]
