# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-30 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_auto_20170930_1555'),
        ('organizacional', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='agenda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='agenda.Agenda', verbose_name='agenda'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='organizacional.Sucursal', verbose_name='sucursal'),
        ),
    ]
