# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacional', '0002_auto_20170606_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='tipo',
            field=models.CharField(choices=[('M', 'medico'), ('A', 'administrativo')], max_length=2, verbose_name='tipo'),
        ),
    ]
