# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacional', '0003_auto_20170606_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='tipo',
            field=models.CharField(choices=[('M', 'medico'), ('A', 'administrativo')], default='A', max_length=2, verbose_name='tipo'),
        ),
    ]
