# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacional', '0004_auto_20170612_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='duracion_cita',
            field=models.DurationField(blank=True, help_text='La duración de la citas en minutos', null=True, verbose_name='duración de las citas'),
        ),
    ]
