# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacional', '0005_empleado_duracion_cita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='duracion_cita',
            field=models.DurationField(blank=True, help_text='Ingresar duración de la forma HH:MM:SS', null=True, verbose_name='duración de las citas'),
        ),
    ]
