# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
            ],
            options={
                'verbose_name_plural': 'empresas',
                'verbose_name': 'empresa',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
            ],
            options={
                'verbose_name_plural': 'servicios',
                'verbose_name': 'servicio',
            },
        ),
    ]
