# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 22:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='plan')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='servicios.Empresa', verbose_name='empresa')),
                ('servicios', models.ManyToManyField(related_name='planes', to='servicios.Servicio', verbose_name='servicios')),
            ],
            options={
                'verbose_name_plural': 'planes',
                'verbose_name': 'plan',
            },
        ),
    ]
