# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-01 00:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('historias', '0001_initial'),
        ('servicios', '0002_empresa_instituciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='formato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='historias.Formato', verbose_name='formato'),
        ),
    ]
