# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_servicio_formato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='codigo',
            field=models.CharField(blank=True, max_length=100, verbose_name='código'),
        ),
    ]
