# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipio',
            name='departamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='municipios', to='globales.Departamento', verbose_name='departamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poblado',
            name='municipio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='poblados', to='globales.Municipio', verbose_name='municipio'),
            preserve_default=False,
        ),
    ]
