# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cie',
            name='nombre',
            field=models.CharField(max_length=400, verbose_name='nombre'),
        ),
    ]
