# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 14:44
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import historias.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adjunto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=historias.models.archivo_adjunto_path, verbose_name='archivo')),
            ],
            options={
                'verbose_name': 'adjunto',
                'verbose_name_plural': 'adjuntos',
            },
        ),
        migrations.CreateModel(
            name='Formato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('contenido', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'verbose_name': 'formato',
                'verbose_name_plural': 'formatos',
            },
        ),
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', django.contrib.postgres.fields.jsonb.JSONField()),
                ('terminada', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'historia',
                'verbose_name_plural': 'historias',
            },
        ),
    ]
