# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-01 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4, verbose_name='codigo')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
            ],
            options={
                'verbose_name_plural': 'Cies',
                'verbose_name': 'Cie',
            },
        ),
        migrations.RenameField(
            model_name='formato',
            old_name='formato',
            new_name='contenido',
        ),
    ]
