# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('historias', '0001_initial'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historia',
            name='sesion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pacientes.Sesion', verbose_name='sesion'),
        ),
        migrations.AddField(
            model_name='adjunto',
            name='historia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='historias.Historia', verbose_name='historia'),
        ),
    ]
