# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-01 17:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historias', '0002_auto_20170701_1723'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cie',
        ),
    ]
