# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 04:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_auto_20170825_0432'),
        ('historias', '0002_auto_20170825_0008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historia',
            name='servicio_orden',
        ),
        migrations.AddField(
            model_name='historia',
            name='sesion',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='pacientes.Sesion', verbose_name='sesion'),
            preserve_default=False,
        ),
    ]
