# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 20:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historias', '0002_auto_20171004_1444'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historia',
            options={'ordering': ['-sesion'], 'verbose_name': 'historia', 'verbose_name_plural': 'historias'},
        ),
    ]
