# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-01 17:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historias', '0003_delete_cie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historia',
            old_name='servicio',
            new_name='servicio_orden',
        ),
    ]
