# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historias', '0003_auto_20171102_2022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historia',
            options={'ordering': ['-sesion'], 'permissions': [('puede_agregar_triage', 'Puede agregar triage')], 'verbose_name': 'historia', 'verbose_name_plural': 'historias'},
        ),
        migrations.AddField(
            model_name='formato',
            name='triage',
            field=models.BooleanField(default=False, help_text='Indica si la historia incluye triage', verbose_name='triage'),
        ),
    ]
