# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 21:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historias', '0004_auto_20170701_1757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historia',
            old_name='historia',
            new_name='contenido',
        ),
    ]
