# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 23:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import historias.models


class Migration(migrations.Migration):

    dependencies = [
        ('historias', '0005_auto_20170712_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjunto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=historias.models.archivo_adjunto_path, verbose_name='archivo')),
                ('historia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='historias.Historia', verbose_name='historia')),
            ],
            options={
                'verbose_name_plural': 'adjuntos',
                'verbose_name': 'adjunto',
            },
        ),
    ]
